test leafiterator
test faild
cause: https://github.com/iotexproject/iotex-core/blob/master/db/trie/mptrie/leafiterator.go#L50
detail:
=== RUN   TestIterator
    TestIterator: leafiterator_test.go:55:
        	Error Trace:	leafiterator_test.go:55
        	Error:      	Not equal:
        	            	expected: "coin"
        	            	actual  : "coincoin"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-coin
        	            	+coincoin
        	Test:       	TestIterator
        	Messages:   	key: iotex
--- FAIL: TestIterator (0.00s)